### PR TITLE
Temporary workaround / fallback for module apply error

### PR DESCRIPTION
**Pull request by Barragek0**
Temporary fallback for issue #8

### CODE REVIEW

**Comment by FrancoisMentec** [comment]
Nice. Out of curiosity, how did you found out this solution?

**Comment by Barragek0** [comment]
> 
> 
> Nice. Out of curiosity, how did you found out this solution?

It was commented out above the Module line so I figured it was used in the past to do the same thing. I have no idea what that issue is with Module, looked all over the place but could find barely any information on it.

**Comment by FrancoisMentec** [comment]
So the code you uncommented was an attempt at pasting text in pob.party which failed. The Module call is the one that worked, but I kept the DataTransfer in a comment just in case I would need it one day. I have no idea why the Module call now causes this error. But the fact the data transfer now works (probably due to an update of pob.party), makes me wonder if I could finally use it to directly paste a build code in the import field on pob.party. But for now, I'm too busy grinding ultimatum.

I think pob.party changed the way it handles pasting. The Module call would send the text directly to the asm, while the Data Transfer would emulate a pasting event and let pob.party pass the text to the asm. But for some reason, it didn't work back then, or maybe it just didn't work on one browser (chrome/firefox), can't remember.

**Comment by Barragek0** [comment]
> 
> 
> So the code you uncommented was an attempt at pasting text in pob.party which failed. The Module call is the one that worked, but I kept the DataTransfer in a comment just in case I would need it one day. I have no idea why the Module call now causes this error. But the fact the data transfer now works (probably due to an update of pob.party), makes me wonder if I could finally use it to directly paste a build code in the import field on pob.party. But for now, I'm too busy grinding ultimatum.
> 
> I think pob.party changed the way it handles pasting. The Module call would send the text directly to the asm, while the Data Transfer would emulate a pasting event and let pob.party pass the text to the asm. But for some reason, it didn't work back then, or maybe it just didn't work on one browser (chrome/firefox), can't remember.

Interesting, excited to see if that would allow using the pob code in the extension in the future so I don't have to load up pob.party all the time to get that link for the extension to use.

**Pull request merged**
